version: '3.1'

services:
  db:
    image: postgres:13.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cuna
    ports:
      - 5432:5432
  redis:
    image: redis:6.2
    command: redis-server --requirepass redis
    ports:
      - 6379:6379
