[package]
name = "common_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
common_domain = { path = "../common_domain" }
serde = { version = "1.0", features = ["derive"] }
validator = { version = "0.15", features = ["derive"] }
sqlx = "0.6"
regex = "1.6.0"
