[package]
name = "auth_domain"
version = "0.1.0"
edition = "2021"

[dependencies]
auth_adapters = { path = "../auth_adapters" }
common_domain = { path = "../../common/common_domain" }
with_executor = { path = "../../macro/with_executor" }
