[package]
name = "profile_domain"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
async_fn_traits = "0.1.1"
common_domain = { path = "../../common/common_domain" }
with_executor = { path = "../../macro/with_executor" }
