[package]
name = "auth_adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
common_domain = { path = "../../common/common_domain" }
auth_domain = { path = "../auth_domain" }
sqlx = { version = "0.6", features = [
  "runtime-actix-rustls",
  "postgres",
  "chrono",
  "offline",
] }
