[package]
name = "auth_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
chrono = "0.4.19"
sqlx = { version = "0.6", features = [
  "runtime-actix-rustls",
  "postgres",
  "chrono",
] }
